### ISSUE TITLE
linking problem related with std::(experimental::)filesystem with mingw-w64/gcc 7.3 on windows 10

### ISSUE THREAD

**Issue by crillion** [cnjinhao/nana#408]
Hi,

   I am trying to compile a nana program with nana 1.7.0 and gcc 7.3.0 from mingw-w64 on windows 10. This is the program:

`
#include <nana/gui.hpp>

int main()
{
	nana::exec();
}
`

If I compile it with the command: 

`
g++ -pedantic -std=c++17 -Wall -Wextra -Werror=return-type -Wshadow=local -Wempty-body -fdiagnostics-color -s -Os program.cpp -o program_gpp.exe -LC:\programs\mingw-w64\x86_64-7.3.0-posix-seh-rt_v6-rev0\mingw64\lib -I../../../../external/nana/nana_1_7_0/nana/include -L../../../../external/nana/nana_1_7_0/nana -lnana -lgdi32 -lcomdlg32 -lstdc++fs -lKtmW32 -lws2_32
`

I get the error:

C:/programs/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/libstdc++fs.a(path.o):(.rdata$_ZNSt12experimental10filesystem2v17__cxx114path19preferred_separatorE+0x0): multiple definition of `std::experimental::filesystem::v1::__cxx11::path::preferred_separator'
../../../../external/nana/nana_1_7_0/nana/libnana.a(filebox.cpp.obj):filebox.cpp:(.rdata$_ZNSt12experimental10filesystem2v17__cxx114path19preferred_separatorE[_ZNSt12experimental10filesystem2v17__cxx114path19preferred_separatorE]+0x0): first defined here
collect2.exe: error: ld returned 1 exit status

If I remove from the compiling command the -lstdc++fs linking option, so that the compilation script becomes:

`
g++ -pedantic -std=c++17 -Wall -Wextra -Werror=return-type -Wshadow=local -Wempty-body -fdiagnostics-color -s -Os program.cpp -o program_gpp.exe -LC:\programs\mingw-w64\x86_64-7.3.0-posix-seh-rt_v6-rev0\mingw64\lib -I../../../../external/nana/nana_1_7_0/nana/include -L../../../../external/nana/nana_1_7_0/nana -lnana -lgdi32 -lcomdlg32 -lKtmW32 -lws2_32
`

 I get instead a long error thread:

../../../../external/nana/nana_1_7_0/nana/libnana.a(bedrock_windows.cpp.obj): In function `std::experimental::filesystem::v1::__cxx11::path::path(std::experimental::filesystem::v1::__cxx11::path&&)':
C:/programs/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/c++/experimental/bits/fs_path.h:185: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
../../../../external/nana/nana_1_7_0/nana/libnana.a(bedrock_windows.cpp.obj): In function `std::experimental::filesystem::v1::__cxx11::path::clear()':
C:/programs/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/lib/gcc/x86_64-w64-mingw32/7.3.0/include/c++/experimental/bits/fs_path.h:297: undefined reference to `std::experimental::filesystem::v1::__cxx11::path::_M_split_cmpts()'
(...) many many other similar errors 

The same cpp program compiles fine on linux (gcc 7.3.1 on opensuse 15.1).

Thanks,

      Marco

**Comment by cnjinhao** [comment]
It seems that the nana isn't built with `-std=c++17`. Please keep this option same between nana and your program.

If you still have issues on `std::filesystem` with `-std=c++17`, please read this https://github.com/cnjinhao/nana/wiki/Troubleshooting-MinGW

**Comment by crillion** [comment]
Thanks a lot Jinhao,

     with those instructions I could fix my problem.

I included -std=c++17 gcc option in the cmake command; and also added to the cmake command the switch -DNANA_CMAKE_NANA_FILESYSTEM_FORCE=1.

Now I could compile the library and my program.

         Marco

**Comment by qPCR4vir** [comment]
Hi, I installed MSYS2 with mingw-w64-x86_64-gcc following https://github.com/cnjinhao/nana/wiki/Troubleshooting-MinGW and now my program stop in 
https://github.com/cnjinhao/nana/blob/hotfix-1.7/source/gui/filebox.cpp#L1353
`auto len = ::GetCurrentDirectory(0, nullptr);
What can I do?`

**Comment by cnjinhao** [comment]
Hi, @qPCR4vir I can't reproduce the issue that stops at `auto len = ::GetCurrentDirectory(0, nullptr);`
Was a correct libnana.a linked against to your program?

BTW: Code::Blocks is too buggy. I encountered a `undefined reference` errors on `std::filesystem`, after investigation, there was a `-DNANA_FILESYSTEM_FORCE` option which is undesired, but I checked project's `Build options...` and global compiler settings, I couldn't find the option. So I openned Code::Blocks' `default.conf`, and found the option in the file. After removing the option, the error gone away.

**Comment by qPCR4vir** [comment]
hmmm.. debugging:
here:
```
	folderbox::folderbox(window owner, const path_type& init_path, std::string title)
		: impl_(new implement{ owner, fs::canonical(init_path).make_preferred(), title, false})
	{}
```
[canonical need an existing path](https://en.cppreference.com/w/cpp/filesystem/canonical):
replaced by `weakly_canonical` https://github.com/cnjinhao/nana/pull/410

**Comment by cnjinhao** [comment]
Improved the support of filesystem on C++11/14
