### ISSUE TITLE
Hotfix not working? mutex errors!!!

### ISSUE THREAD

**Issue by ducklin5** [cnjinhao/nana#111]
MINGW64 /c/libs/nana/build/bin/netbeans8 (origin/hotfix-1.3)
$ mingw32-make.exe
Scanning dependencies of target nana
[  1%] Building CXX object CMakeFiles/nana.dir/source/any.cpp.obj
[  2%] Building CXX object CMakeFiles/nana.dir/source/basic_types.cpp.obj
[  3%] Building CXX object CMakeFiles/nana.dir/source/charset.cpp.obj
[  5%] Building CXX object CMakeFiles/nana.dir/source/datetime.cpp.obj
[  6%] Building CXX object CMakeFiles/nana.dir/source/deploy.cpp.obj
[  7%] Building CXX object CMakeFiles/nana.dir/source/internationalization.cpp.obj
C:\libs\nana\source\internationalization.cpp:254:4: error: 'recursive_mutex' in namespace 'std' does not name a type
    std::recursive_mutex mutex;
    ^
C:\libs\nana\source\internationalization.cpp: In function 'void nana::internationalization_parts::set_eval(nana::window, nana::i18n_eval&&)':
C:\libs\nana\source\internationalization.cpp:267:20: error: 'recursive_mutex' is not a member of 'std'
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                    ^
C:\libs\nana\source\internationalization.cpp:267:20: error: 'recursive_mutex' is not a member of 'std'
C:\libs\nana\source\internationalization.cpp:267:40: error: template argument 1 is invalid
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                                        ^
C:\libs\nana\source\internationalization.cpp:267:46: error: invalid type in declaration before '(' token
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                                              ^
C:\libs\nana\source\internationalization.cpp:267:51: error: 'struct nana::internationalization_parts::eval_manager' has no member named 'mutex'
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                                                   ^
C:\libs\nana\source\internationalization.cpp: In lambda function:
C:\libs\nana\source\internationalization.cpp:274:22: error: 'recursive_mutex' is not a member of 'std'
      std::lock_guard<std::recursive_mutex> lockgd(eval_mgr.mutex);
                      ^
C:\libs\nana\source\internationalization.cpp:274:22: error: 'recursive_mutex' is not a member of 'std'
C:\libs\nana\source\internationalization.cpp:274:42: error: template argument 1 is invalid
      std::lock_guard<std::recursive_mutex> lockgd(eval_mgr.mutex);
                                          ^
C:\libs\nana\source\internationalization.cpp:274:50: error: invalid type in declaration before '(' token
      std::lock_guard<std::recursive_mutex> lockgd(eval_mgr.mutex);
                                                  ^
C:\libs\nana\source\internationalization.cpp:274:60: error: 'struct nana::internationalization_parts::eval_manager' has no member named 'mutex'
      std::lock_guard<std::recursive_mutex> lockgd(eval_mgr.mutex);
                                                            ^
C:\libs\nana\source\internationalization.cpp: In function 'void nana::internationalization_parts::use_eval()':
C:\libs\nana\source\internationalization.cpp:286:20: error: 'recursive_mutex' is not a member of 'std'
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                    ^
C:\libs\nana\source\internationalization.cpp:286:20: error: 'recursive_mutex' is not a member of 'std'
C:\libs\nana\source\internationalization.cpp:286:40: error: template argument 1 is invalid
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                                        ^
C:\libs\nana\source\internationalization.cpp:286:46: error: invalid type in declaration before '(' token
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                                              ^
C:\libs\nana\source\internationalization.cpp:286:51: error: 'struct nana::internationalization_parts::eval_manager' has no member named 'mutex'
    std::lock_guard<std::recursive_mutex> lock(mgr.mutex);
                                                   ^
CMakeFiles\nana.dir\build.make:187: recipe for target 'CMakeFiles/nana.dir/source/internationalization.cpp.obj' failed
mingw32-make[2]: *** [CMakeFiles/nana.dir/source/internationalization.cpp.obj] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/nana.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/nana.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by qPCR4vir** [comment]
hi !
I have not to much experience, but in the last month I used Clion with MinGW. What versions are you using? You need 4.9 or better.
As you can see, it compile in travis with gcc 4.9 and 5.2
You need to correctly link with pthreads, etc... Maybe you fork nana and I can see exaclty what are you doing?
You may find this interesting: https://github.com/qPCR4vir/nana/commit/52510b265a88ec42cadcb5f2eaad44461a33101f

and in general: #109

**Comment by kirbyfan64** [comment]
Your GCC versiob might be too old. I think the latest GCC that MinGW comes with is 4.8. There's an [experimental 4.9 available](https://sourceforge.net/projects/mingw/files/MinGW/Base/gcc/Version4/experimental/) that you can use; you might have better luck using [Clang](http://llvm.org/releases/download.html#3.7.1) or [TDM-GCC](http://tdm-gcc.tdragon.net) (a Windows version of GCC 5.1).

**Comment by cnjinhao** [comment]
What version of your GCC? it seems that your GCC is newer than 4.8.0, because Nana will enable std mutex workarounds(boost.thread or MEGANZ std thread) when GCC is older than 4.8.1. Try again with "-std=c++11".

**Comment by ducklin5** [comment]
The previous one was an attempt to build  with MinGW/TDM (32bit)--> MinGW Stable, C/C++
(provides g++ and gcc 4.81)

Im on windows 7 64-bit
which version of TDM-GCC should I use?  installation provides several
which git should I pull?
where would i set "-std=c++11"?
Does this project have an IRC channel?
Id prefer to stick to Netbeans, but if it comes to it ill try Clion

**Comment by qPCR4vir** [comment]
with MinGW/gcc 4.8.1 you can compile nana, but you need to provide threads:
see this [mingw-std-threads](https://github.com/meganz/mingw-std-threads) 
you can use it or Boost, and select in nana the corresponding option.

But it will be much better if you use what @kmribti pointed: [TDM-GCC 64, gcc 5.1.0](http://tdm-gcc.tdragon.net/). It has better c+11 support.
Oh, yes I'm remembering. TDM-GCC have a GUI for installation... you my need to select threads support. I installed 64b compiler but with both 64 and 32b runtime to compile my programs with those options. This will install libwinpthread_64-1 and libwinpthread-1. And libstdc++_64-6 and libstdc++-6.

And if you use the CMakeList.txt provided by nana all will be linked OK. (I hope)
Well, please, try Netbeans, we will have one more option :-)

> which git should I pull?
what you mind? 

We have:
http://www.nanapro.org/en-us/
http://nanapro.org/en-us/discuss.htm

**Comment by ducklin5** [comment]
Yes!! I tried the version you said
MinGW-w64/TDM64 (32-bit and 64-bit) --> TDM-GCC worked, it built the library, but i had to make sure libpng, libjpeg and the demos were disable. Now to check if the library works.
After an attempt to use netbeans, I remembered why I stopped using it : http://stackoverflow.com/questions/30154115/fltk-complains-about-gcc-on-windows
I'll have to try with something else, I have eclipse luna installed so I'll try with that.

**Comment by kirbyfan64** [comment]
@ducklin5 What exactly does that link have to do with NetBeans?

**Comment by ducklin5** [comment]
9 months ago in the section under "EDIT" I wrote. 
"Something (most probably cygwin) keeps breaking my mingw gcc program and every time its "broken" I get black vcc1.exe windows. Then i must replace the mingw folder to get it working again, this happens mostly when i open netbeans. I just dont know how to fix this, so ive just been avoiding cygwin and netbeans."
This isn't a nana problem so no need to worry about it.

**Comment by kirbyfan64** [comment]
Huh, that's really weird...I posted a comment to try and help.

**Comment by ducklin5** [comment]
Finally set up nana with eclipse and it works!

**Comment by qPCR4vir** [comment]
Congratulation!
Please tell us how... [please here...](https://github.com/qPCR4vir/nana-docs/wiki/Nana-in-Eclipse)
